### ISSUE TITLE
Chybějící GPS souřadnice

### ISSUE THREAD

**Issue by kukulich** [CzechTourism/kzn-content-api#1]
V API chybí GPS souřadnice, je proto nějaký důvod?

**Comment by hanysek** [comment]
Dobrý den. GPS pozice přidány. Viz dokumentace. Dík za upozornění.

**Comment by kukulich** [comment]
@hanysek Díky. Je možné přidat i další parametry událostí?

**Comment by hanysek** [comment]
Toto je dotaz na Kudy z nudy/CzechTourism. Jsou tam omezení ve vztahu k ochraně údajů, právní otázky, atd:(

**Comment by kukulich** [comment]
Jasně, rozumím. Ještě se zeptám, zda teď nevadí, že ty GPS nejsou v podmínkách: https://www.kudyznudy.cz/podminky-poskytovani-pristupu-k-api

**Comment by hanysek** [comment]
Dík za upozornění. Imho to není tolik podstatné. Předám dále, aby se i tam upravilo.
